# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTunesSearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunesSearchApp

	pod 'IQKeyboardManager'
	pod 'Alamofire', '~> 5.5'
	pod 'Kingfisher', '~> 7.0'
end
